name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - 
      uses: actions/checkout@v3
    
    - 
      name: Build and push Docker images using Docker Compose
      run: |
        docker-compose -f docker-compose.yml build
        docker tag backend vihidun/depresio_backend:latest
        docker tag frontend vihidun/depresio_frontend:latest
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker push vihidun/depresio_backend:latest
        docker push vihidun/depresio_frontend:latest
      env:
        DOCKER_BUILDKIT: 1
      working-directory: ${{ github.workspace }}
    
    - 
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - 
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    

