name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # You had v3, but v2 is the latest version as of my knowledge cutoff date.

    - name: Build and push Docker images using Docker Compose
      run: |
        docker-compose -f docker-compose.yml build
        docker-compose -f docker-compose.yml push
      env:
        DOCKER_BUILDKIT: 1
      working-directory: ${{ github.workspace }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image to Docker Hub
      uses: docker/build-push-action@v5
      with:
        context: .  # Use the current directory as the build context.
        push: true
        tags: vihidun/depresio_1.0:latest
