name: Vercel CD

on:
  # workflow_run:
  #   workflows: [Docker Image CI]
  #   types:
  #     - completed
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

  steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Vercel
        working-directory: frontend
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npm install --global vercel
          vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
          vercel build --token=$VERCEL_TOKEN
          vercel deploy --prebuilt --token=$VERCEL_TOKEN
